In [1]:
options(jupyter.rich_display = FALSE)

# Assignment 1: R Basics and Control Flow

## POP77001 Computer Programming for Social Scientists

## Before submission

- Make sure that you can run all cells without errors
- You can do it by clicking `Kernel`, `Restart & Run All` in the menu above
- Make sure that you save the output by pressing Command+S / CTRL+S
- Rename the file from `04_assignment.ipynb` to `04_assignment_studentnumber_firstname_lastname.ipynb`
- Use Firefox browser for submitting your Jupyter notebook on Blackboard

## Exercise 1: Subsetting (20 points)

Write 3 separate subsetting operations to extract the following elements from the list below:
- All consonants from the first character vector
- Second columns in all dimensions from the array A
- Odd rows from the matrix M

In [2]:
l <- list(
    mapply(assign, letters, 1:26),
    A = array(1:60, c(5,2,3)),
    M = matrix(1:50, c(10,5))
)
l

[[1]]
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$A
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$M
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50


In [3]:
# As there are considerably more consonants than vowels in the alphabet
# we can select all of them by excluding vowels from the vector
l[[1]][-which(names(l[[1]]) %in% c("a", "e", "i", "o", "u"))]

 b  c  d  f  g  h  j  k  l  m  n  p  q  r  s  t  v  w  x  y  z 
 2  3  4  6  7  8 10 11 12 13 14 16 17 18 19 20 22 23 24 25 26 

In [4]:
# Specifying drop=FALSE keeps the original structure of the array intact
# rather than collapsing it in a 2-dimensional matrix
l$A[,2,,drop=FALSE]

, , 1

     [,1]
[1,]    6
[2,]    7
[3,]    8
[4,]    9
[5,]   10

, , 2

     [,1]
[1,]   16
[2,]   17
[3,]   18
[4,]   19
[5,]   20

, , 3

     [,1]
[1,]   26
[2,]   27
[3,]   28
[4,]   29
[5,]   30


In [5]:
# We can subet odd rows by passing a 2-element logical vector with the first element being TRUE
l$M[c(TRUE, FALSE),]

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    11   21   31   41  
[2,] 3    13   23   33   43  
[3,] 5    15   25   35   45  
[4,] 7    17   27   37   47  
[5,] 9    19   29   39   49  

## Exercise 2: Working with vectors  (20 points)

Look at the vector below. What is its type? Convert it into numeric. Note that some values get missing due to letter `o` used instead of digit `0`. What proportion of the vector elements did we fail to convert correctly? Now let us fix this issue. Using either subsetting and assignment or `ifelse()` function replace all `NA`s in the converted numeric vector into `0` (zeros).

In [2]:
set.seed(2022)
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)
vec

[1] "o" "0" "o" "o" "0" "o" "0" "o" "1" "0" "o" "1" "0" "o" "0" "1" "1" "o"
 [19] "1" "0" "0" "o" "1" "o" "0" "o" "o" "0" "1" "o" "o" "0" "o" "1" "0" "0"
 [37] "1" "o" "o" "0" "o" "1" "o" "o" "1" "0" "o" "1" "0" "1" "1" "o" "o" "0"
 [55] "1" "o" "0" "0" "o" "o" "o" "1" "0" "o" "0" "1" "o" "0" "0" "1" "1" "0"
 [73] "0" "1" "0" "o" "o" "0" "1" "o" "1" "o" "0" "o" "1" "o" "1" "o" "o" "o"
 [91] "o" "0" "0" "1" "o" "0" "1" "1" "0" "1"

In [7]:
# The type of this vector is character.
#
# Despite the presence of zeros and ones, as you can see 
# they are enclosed in quotation marks. We can also 
# explicitly check the type of this vector with typeof()
# function.
typeof(vec)

[1] "character"

In [8]:
# Before conversion let's check how many elements with
# each value we have in the vector.
table(vec)

vec
 0  1  o 
32 28 40 

In [9]:
# Note that we lost some values in this vector,
# as they couldn't be properly converted into numbers
# and, thus, were replacted with NA value.
vec <- as.numeric(vec)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”


In [10]:
# To calculate the proportion of NAs, we can
# sum up the TRUE values in the output of 
# is.na() function, which get implicitly
# converted into 1s and then divide it
# by the length of the vector.
sum(is.na(vec))/length(vec)

[1] 0.4

In [11]:
# Alternatively, recall that TRUE and FALSE correspond to 1 and 0.
# This means that we can directly apply mean() function to determine
# the proportion of TRUE values in the vector results of checking for NAs.
mean(is.na(vec))

[1] 0.4

In [12]:
# When applying ifelse() function
# we specify whether of not a given
# element is NA as a boolean test, 0
# as a replacement value for instances
# where it is and the original values of vec
# as a plug-in value for cases where it is not.
vec <- ifelse(is.na(vec), 0, vec)

In [13]:
# Finally, we can compare the composition of the vector
# after the changes we have made to the original one
table(vec)

vec
 0  1 
72 28 

## Exercise 3: Vectorized operations  (20 points)

Using function `mean()` calculate the proportion of book titles in the vector below that have more than 10 characters in them (including whitespaces).

Tip: You can use `nchar()` function to calculate the number of characters in a vector

In [14]:
books <- c(
  "Dubliners",
  "Ulysses",
  "War and Peace",
  "Normal People",
  "Crime and Punishment",
  "The Picture of Dorian Gray"
)

In [15]:
# As we have seen above, mean() function 
# when applied to logical vectors offers 
# a convenient way of calculating proportions
mean(nchar(books) > 10)

[1] 0.6666667

## Exercise 4: Attributes and factors  (20 points)

Suppose you read in a variable which represents education of survey respondents. After consulting the codebook for this survey you determined that specific values that the variable takes are coded as follows:

- `0` - No formal education
- `1` - Primary Education
- `2` - Secondary Education
- `3` - College Education
- `4` - Post-graduate Education

Convert the variable `educ` below into a factor variable with each value coded explicitly as one of the education levels. Tabulate the variable using `table()` function. Change the order of the levels of this factor variable such that the most common education level is the first (baseline/reference) category (you can leave other education levels in their original order). Tabulate the variable again.   

In [16]:
set.seed(2022)
educ <- rpois(1000, 2)
educ <- ifelse(educ > 4, 4, educ)

In [17]:
# As before, let's first check the distribution
# of different values in the vector (variable)
# before making any changes.
table(educ)

educ
  0   1   2   3   4 
140 274 267 181 138 

In [18]:
# We convert this numeric vector into a factor
# by using the function factor() and explicitly
# providing what level of education each number
# corresponds to.
#
# Note that this expression can be quite long,
# so for readability reasons we break it up across
# multiple lines.
educ <- factor(
  educ,
  labels = c(
    "No formal education",
    "Primary Education",
    "Secondary Education",
    "College Education",
    "Post-graduate Education"
  ))

In [19]:
# You can see that the distriubtion hasn't changed,
# but, importantly, our vector now consists of different
# levels of categorical variable rather than numbers.
table(educ)

educ
    No formal education       Primary Education     Secondary Education 
                    140                     274                     267 
      College Education Post-graduate Education 
                    181                     138 

In [20]:
# While we can manually extract the name of the level 
# with the highest number of observations, it is much
# less error-prone and scalable to do that automatically.
names(which.max(table(educ)))

[1] "Primary Education"

In [21]:
# Here we are using relevel() function on our factor variable
# to change the reference category. Instead of manually
# supplying the name of the most common category, we are 
# calculating it automatically to make our code more robust
# and reusable.
educ <- relevel(educ, ref = names(which.max(table(educ))))

In [22]:
table(educ)

educ
      Primary Education     No formal education     Secondary Education 
                    274                     140                     267 
      College Education Post-graduate Education 
                    181                     138 

## Exercise 5: Conditional statements and loops  (20 points)

[Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) is a string distance metric that measures how many transformations (insertion, deletion, substitution) are required to convert one string into another. For example, consider words 'cat' and 'can'. Letter 't' in the first word can be substituted with a character 'n' in order for the two words to become identical.

For classical Levenshtein distance each of the transformations has the same cost of 1. In other words, the distance (of 1) is the same between the word pairs 'cat' - 'can' and 'cat' - 'cats'.

Below you can see two character vectors that were transformed to have a single letter as an individual element. Write a loop to compare each of the elements from one string to each of the elements from another string while keeping track of the number of transformations. Print out the result of the transformations count.

In [23]:
char_1 <- unlist(strsplit("kitten", split = ""))
char_2 <- unlist(strsplit("sitting", split = ""))

In [24]:
char_1

[1] "k" "i" "t" "t" "e" "n"

In [25]:
char_2

[1] "s" "i" "t" "t" "i" "n" "g"

In [26]:
# Initiate a variable that would hold Levenshtein distance
lv_dist <- 0
# We will iterate over a longer vector (char_2)
for (i in seq_along(char_2)) {
    if (is.na(char_1[i])) {
        lv_dist <- lv_dist + 1
    } else if (char_2[i] != char_1[i]) {
        lv_dist <- lv_dist + 1
    } else {
        next
    }
}

In [27]:
lv_dist

[1] 3